### ISSUE TITLE
Using Panikk causes a crash.

### ISSUE THREAD

**Issue by dertruffel** [LandenStephenss/Panikk#11]
Simple discord crash. If there is a location where logs are logged, i can send them.

**Comment by LandenStephenss** [comment]
not a panikk issue, panikk uses powercord functions and if it is crashing for some reason then that's most likely because of powercord. Nothing i really do is able to cause a crash, but you can see logs by pressing `ctrl + shift + i`, if it happens to be panikk related you can open another issue with the screenshots showing the error.
